### ISSUE TITLE
Crash when opening project + only compiles on second try

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1555]
Project sent via email.

Crash is happening because of this extension
```cs
public extension Vector2<T>
    where T : operator implicit float
    where float : operator implicit T
{
    public const Self PositiveInfinity = .(float.PositiveInfinity, float.PositiveInfinity);
    public static Self NegativeInfinity => .(float.NegativeInfinity, float.NegativeInfinity);
}
```
this extension is located in `Engine\src\Math\Vector2.bf` line 135
when it was a static property it didn't crash

And before the crashing the project doesn't compile on first try, it throws `Conflicting extension override method 'SinglechildWidget.InitChildren()'` but it works fine with subsequent compiles.

Tested with: Nightly 05/04/2022

**Comment by bfiete** [comment]
Crash fixed at 94a5d7e5e9684d285cbac3a6c43473974fe3abb9
And this e5c432144009a54c708384a1ba19671562dee8bc allows the const field initializer to actually work

**Comment by Fusioon** [comment]
Thanks! Is there anything that can be done about the project not compiling on first try? I don't even know if what i'm doing there is allowed.

**Comment by bfiete** [comment]
Can you check again with the next nightly and see if it's doing that still? Everything seemed to be compiling fine (minus a warning) after the fix...

**Comment by Fusioon** [comment]
hmm, that is weird. i did a pull and self compiled the latest commit (5af381f5) and it is still happening.
this is the output i get on first compile/build after clean:
```
Compiling...
Beef compilation time: 1.42s
ERROR: Conflicting extension override method 'SteelEngine.UI.SinglechildWidget.InitChildren()' at line 39:14 in c:\Users\denis\Desktop\SteelEngine\Editor\src\UI\Widgets\Widget.bf
  public new override void InitChildren()
             ^^^^^^^^
  > See previous override at line 382:24 in c:\Users\denis\Desktop\SteelEngine\Engine\src\UI\Widgets\Widget.bf
   public override void InitChildren()
                        ^^^^^^^^^^^^
ERROR: Conflicting extension override method 'SteelEngine.UI.MultichildWidget.InitChildren()' at line 51:14 in c:\Users\denis\Desktop\SteelEngine\Editor\src\UI\Widgets\Widget.bf
  public new override void InitChildren()
             ^^^^^^^^
  > See previous override at line 531:24 in c:\Users\denis\Desktop\SteelEngine\Engine\src\UI\Widgets\Widget.bf
   public override void InitChildren()
                        ^^^^^^^^^^^^
WARNING(3): Method warning: 'UNSAFE - Using Base64 binary serialization' at line 3:6 in $Emit$SteelEngine:SteelEngine.Vector2<>
 ctx.Serialize(null, data);
     ^
  > See method declaration 'SteelEngine.Serialization.SerializationContext.Serialize<T[2]>(System.String name, T[2] val)' at line 38:15 in c:\Users\denis\Desktop\SteelEngine\Engine\src\Serialization\SerializeContext.bf
   public void Serialize<T>(String name, T val)
               ^^^^^^^^^
2914 modules built, 2904 object files generated
Comptime execution time: 0.13s
Errors: 2. Warnings: 1.
Compile failed.

```

**Comment by bfiete** [comment]
Fixed at e1d7939081446981abf8f8a17d5d5669a4c021a8

There were a couple of extra edges cases I found and fixed.
